server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://eurekaserver:8080/eureka/}

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

#spring:
#  cloud:
#    gateway:
#      discovery.locator:
#        enabled: true
#        lowerCaseServiceId: true
#      routes:
#        - id: book-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/book-service/**
#        - id: author-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/author-service/**
#        - id: review-service
#          uri: http://localhost:8083/
#          predicates:
#            - Path=/review-service/**
#        - id: user-service
#          uri: http://localhost:8084/
#          predicates:
#            - Path=/user-service/**